const data = {
  products: [
    {
      name: "1.5 liter drum",
      category: "Drums",
      image: "/images/Drums/101001.jpg",
      price: "199",
    },
    {
      name: "2.0 liter drum",
      category: "Drums",
      image: "/images/Drums/101002.jpg",
      price: "199",
    },
    {
      name: "3.0 liter drum",
      category: "Drums",
      image: "/images/Drums/101003.jpg",
      price: "199",
    },
    {
      name: "5.0 liter drum",
      category: "Drums",
      image: "/images/Drums/101005.jpg",
      price: "199",
    },
    {
      name: "10.0 liter drum",
      category: "Drums",
      image: "/images/Drums/101010.jpg",
      price: "199",
    },
    {
      name: "Stretch extension hose",
      category: "Hoses",
      image: "/images/Hoses/102020mod2.jpg",
      price: "199",
    },
    {
      name: "Stumpy extension hose",
      category: "Hoses",
      image: "/images/Hoses/102021.jpg",
      price: "199",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100400.jpg",
      price: "199",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100401.jpg",
      price: "199",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100402.jpg",
      price: "199",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100403.jpg",
      price: "199",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100404.jpg",
      price: "199",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100405.jpg",
      price: "199",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100406.jpg",
      price: "199",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100407.jpg",
      price: "199",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100408.jpg",
      price: "199",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100409.jpg",
      price: "199",
    },
  ],
};
