const data = {
  products: [
    {
      name: "1.5 liter drum",
      category: "Drums",
      image: "/images/Drums/101001.jpg",
      price: "199",
      slug: "drum-101001",
      description:
        "The OilSafe 1.5 Liter Drum is ideal for small top-up work, such as small reservoirs and oil filler bottles, particularly when mated with the Mini Spout Lid. Fully interchangeable with any OilSafe lid.",
    },
    {
      name: "2.0 liter drum",
      category: "Drums",
      image: "/images/Drums/101002.jpg",
      price: "199",
      slug: "drum-101002",
      description:
        "This compact OilSafe 2 Liter Drum is ideal for top-up work on small to mid-sized sumps. Fully interchangeable with OilSafe lids these drums have an extra wide neck opening for rapid pouring and easy cleaning.",
    },
    {
      name: "3.0 liter drum",
      category: "Drums",
      image: "/images/Drums/101003.jpg",
      price: "199",
      slug: "drum-101003",
      description:
        "This compact OilSafe 3 Liter Drum is a very practical size for servicing small to mid-range equipment filler applications. Fully interchangeable with OilSafe lids these drums have an extra wide neck opening for rapid pouring and easy cleaning.",
    },
    {
      name: "5.0 liter drum",
      category: "Drums",
      image: "/images/Drums/101005.jpg",
      price: "199",
      slug: "drum-101005",
      description:
        "This OilSafe 5 Liter Drum is an excellent all-round size for a host of standard applications from engines and pumps to turbines and gearboxes. Fully interchangeable with OilSafe lids these drums have an extra wide neck opening for rapid pouring and easy cleaning.",
    },
    {
      name: "10.0 liter drum",
      category: "Drums",
      image: "/images/Drums/101010.jpg",
      price: "199",
      slug: "drum-101010",
      description:
        "This OilSafe 10 Liter Drum is the ideal size for large sump fill applications while still maintaining mobility and ease of use without all the heavy lifting and potential back injuries from lifting larger impractical drums. Fully interchangeable with OilSafe lids, these drums have an extra wide neck opening for rapid pouring and easy cleaning.",
    },
    {
      name: "Stretch extension hose",
      category: "Hoses",
      image: "/images/Hoses/102020mod2.jpg",
      price: "199",
      slug: "hose-102020mod2",
      description:
        "The flexible, Stretch Spout Hose Extension attaches to the OilSafe Stretch Spout Lid. Helping awkward or hard-to-reach fill points easy and fast to access and service. The addition of the Stretch Hose Extension to the outlet spout of the Stretch Spout Lid also eliminates the need for funnels, which are notorious for attracting contaminants. The hose can be removed from the fittings and the length cut to suit the application.",
    },
    {
      name: "Stumpy extension hose",
      category: "Hoses",
      image: "/images/Hoses/102021.jpg",
      price: "199",
      slug: "hose-102021",
      description:
        "The flexible, Stumpy Spout Hose Extension attaches to the OilSafe Stumpy Spout Lid. Helping awkward or hard-to-reach fill points easy and fast to access and service. The addition of the Stumpy Hose Extension to the outlet spout of the Stumpy Spout Lid also eliminates the need for funnels, which are notorious for attracting contaminants. The hose can be removed from the fittings and the length cut to suit the application.",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100400.jpg",
      price: "199",
      slug: "mini-spout-lid-100400",
      description:
        "The OilSafe Mini Spout Lid has an outlet diameter of 1/4' (7mm), making it ideal for lubrication jobs where equipment fill holes are small such as constant level oilers and machine tools.",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100401.jpg",
      price: "199",
      slug: "mini-spout-lid-100401",
      description:
        "The OilSafe Mini Spout Lid has an outlet diameter of 1/4' (7mm), making it ideal for lubrication jobs where equipment fill holes are small such as constant level oilers and machine tools.",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100402.jpg",
      price: "199",
      slug: "mini-spout-lid-100402",
      description:
        "The OilSafe Mini Spout Lid has an outlet diameter of 1/4' (7mm), making it ideal for lubrication jobs where equipment fill holes are small such as constant level oilers and machine tools.",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100403.jpg",
      price: "199",
      slug: "mini-spout-lid-100403",
      description:
        "The OilSafe Mini Spout Lid has an outlet diameter of 1/4' (7mm), making it ideal for lubrication jobs where equipment fill holes are small such as constant level oilers and machine tools.",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100404.jpg",
      price: "199",
      slug: "mini-spout-lid-100404",
      description:
        "The OilSafe Mini Spout Lid has an outlet diameter of 1/4' (7mm), making it ideal for lubrication jobs where equipment fill holes are small such as constant level oilers and machine tools.",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100405.jpg",
      price: "199",
      slug: "mini-spout-lid-100405",
      description:
        "The OilSafe Mini Spout Lid has an outlet diameter of 1/4' (7mm), making it ideal for lubrication jobs where equipment fill holes are small such as constant level oilers and machine tools.",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100406.jpg",
      price: "199",
      slug: "mini-spout-lid-100406",
      description:
        "The OilSafe Mini Spout Lid has an outlet diameter of 1/4' (7mm), making it ideal for lubrication jobs where equipment fill holes are small such as constant level oilers and machine tools.",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100407.jpg",
      price: "199",
      slug: "mini-spout-lid-100407",
      description:
        "The OilSafe Mini Spout Lid has an outlet diameter of 1/4' (7mm), making it ideal for lubrication jobs where equipment fill holes are small such as constant level oilers and machine tools.",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100408.jpg",
      price: "199",
      slug: "mini-spout-lid-100408",
      description:
        "The OilSafe Mini Spout Lid has an outlet diameter of 1/4' (7mm), making it ideal for lubrication jobs where equipment fill holes are small such as constant level oilers and machine tools.",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100409.jpg",
      price: "199",
      slug: "mini-spout-lid-100409",
      description:
        "The OilSafe Mini Spout Lid has an outlet diameter of 1/4' (7mm), making it ideal for lubrication jobs where equipment fill holes are small such as constant level oilers and machine tools.",
    },
    {
      name: "Standard Pump",
      category: "StandardPumps",
      image: "/images/Pumps/102000.jpg",
      price: "199",
      slug: "standard-pump-102000",
      description: "",
    },
    {
      name: "Pump reducer nozzle",
      category: "StandardPumps",
      image: "/images/Pumps/102030.jpg",
      price: "199",
      slug: "pump-reducer-nozzle-102030",
      description: "",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102300.jpg",
      price: "199",
      slug: "premium-pump-102300",
      description: "",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102301.jpg",
      price: "199",
      slug: "premium-pump-102301",
      description: "",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102302.jpg",
      price: "199",
      slug: "premium-pump-102302",
      description: "",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102303.jpg",
      price: "199",
      slug: "premium-pump-102303",
      description: "",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102304.jpg",
      price: "199",
      slug: "premium-pump-102304",
      description: "",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102305.jpg",
      price: "199",
      slug: "premium-pump-102305",
      description: "",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102306.jpg",
      price: "199",
      slug: "premium-pump-102306",
      description: "",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102307.jpg",
      price: "199",
      slug: "premium-pump-102307",
      description: "",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102308.jpg",
      price: "199",
      slug: "premium-pump-102308",
      description: "",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102309.jpg",
      price: "199",
      slug: "premium-pump-102309",
      description: "",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100100.jpg",
      price: "199",
      slug: "storage-lid-100100",
      description: "",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100101.jpg",
      price: "199",
      slug: "storage-lid-100101",
      description: "",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100102.jpg",
      price: "199",
      slug: "storage-lid-100102",
      description: "",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100103.jpg",
      price: "199",
      slug: "storage-lid-100103",
      description: "",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100104.jpg",
      price: "199",
      slug: "storage-lid-100104",
      description: "",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100105.jpg",
      price: "199",
      slug: "storage-lid-100105",
      description: "",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100106.jpg",
      price: "199",
      slug: "storage-lid-100106",
      description: "",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100107.jpg",
      price: "199",
      slug: "storage-lid-100107",
      description: "",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100108.jpg",
      price: "199",
      slug: "storage-lid-100108",
      description: "",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100109.jpg",
      price: "199",
      slug: "storage-lid-100109",
      description: "",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100300.jpg",
      price: "199",
      slug: "stretch-lid-100300",
      description: "",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100301.jpg",
      price: "199",
      slug: "stretch-lid-100301",
      description: "",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100302.jpg",
      price: "199",
      slug: "stretch-lid-100302",
      description: "",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100303.jpg",
      price: "199",
      slug: "stretch-lid-100303",
      description: "",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100304.jpg",
      price: "199",
      slug: "stretch-lid-100304",
      description: "",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100305.jpg",
      price: "199",
      slug: "stretch-lid-100305",
      description: "",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100306.jpg",
      price: "199",
      slug: "stretch-lid-100306",
      description: "",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100307.jpg",
      price: "199",
      slug: "stretch-lid-100307",
      description: "",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100308.jpg",
      price: "199",
      slug: "stretch-lid-100308",
      description: "",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100309.jpg",
      price: "199",
      slug: "stretch-lid-100309",
      description: "",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100500.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100500",
      description: "",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100501.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100501",
      description: "",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100502.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100502",
      description: "",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100503.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100503",
      description: "",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100504.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100504",
      description: "",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100505.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100505",
      description: "",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100506.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100506",
      description: "",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100507.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100507",
      description: "",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100508.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100508",
      description: "",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100509.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100509",
      description: "",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100200.jpg",
      price: "199",
      slug: "utility-lid-100200",
      description: "",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100201.jpg",
      price: "199",
      slug: "utility-lid-100201",
      description: "",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100202.jpg",
      price: "199",
      slug: "utility-lid-100202",
      description: "",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100203.jpg",
      price: "199",
      slug: "utility-lid-100203",
      description: "",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100204.jpg",
      price: "199",
      slug: "utility-lid-100204",
      description: "",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100205.jpg",
      price: "199",
      slug: "utility-lid-100205",
      description: "",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100206.jpg",
      price: "199",
      slug: "utility-lid-100206",
      description: "",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100207.jpg",
      price: "199",
      slug: "utility-lid-100207",
      description: "",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100208.jpg",
      price: "199",
      slug: "utility-lid-100208",
      description: "",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100209.jpg",
      price: "199",
      slug: "utility-lid-100209",
      description: "",
    },
  ],
};

export default data;
