const data = {
  products: [
    {
      name: "1.5 liter drum",
      category: "Drums",
      image: "/images/Drums/101001.jpg",
      price: "199",
      slug: "drum-101001",
      description:
        "The OilSafe 1.5 Liter Drum is ideal for small top-up work, such as small reservoirs and oil filler bottles, particularly when mated with the Mini Spout Lid. Fully interchangeable with any OilSafe lid.",
    },
    {
      name: "2.0 liter drum",
      category: "Drums",
      image: "/images/Drums/101002.jpg",
      price: "199",
      slug: "drum-101002",
    },
    {
      name: "3.0 liter drum",
      category: "Drums",
      image: "/images/Drums/101003.jpg",
      price: "199",
      slug: "drum-101003",
    },
    {
      name: "5.0 liter drum",
      category: "Drums",
      image: "/images/Drums/101005.jpg",
      price: "199",
      slug: "drum-101005",
    },
    {
      name: "10.0 liter drum",
      category: "Drums",
      image: "/images/Drums/101010.jpg",
      price: "199",
      slug: "drum-101010",
    },
    {
      name: "Stretch extension hose",
      category: "Hoses",
      image: "/images/Hoses/102020mod2.jpg",
      price: "199",
      slug: "hose-102020mod2",
    },
    {
      name: "Stumpy extension hose",
      category: "Hoses",
      image: "/images/Hoses/102021.jpg",
      price: "199",
      slug: "hose-102021",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100400.jpg",
      price: "199",
      slug: "mini-spout-lid-100400",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100401.jpg",
      price: "199",
      slug: "mini-spout-lid-100401",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100402.jpg",
      price: "199",
      slug: "mini-spout-lid-100402",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100403.jpg",
      price: "199",
      slug: "mini-spout-lid-100403",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100404.jpg",
      price: "199",
      slug: "mini-spout-lid-100404",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100405.jpg",
      price: "199",
      slug: "mini-spout-lid-100405",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100406.jpg",
      price: "199",
      slug: "mini-spout-lid-100406",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100407.jpg",
      price: "199",
      slug: "mini-spout-lid-100407",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100408.jpg",
      price: "199",
      slug: "mini-spout-lid-100408",
    },
    {
      name: "Mini Spout Lid",
      category: "MiniSpoutLid",
      image: "/images/MiniSpoutLid/100409.jpg",
      price: "199",
      slug: "mini-spout-lid-100409",
    },
    {
      name: "Standard Pump",
      category: "StandardPumps",
      image: "/images/Pumps/102000.jpg",
      price: "199",
      slug: "standard-pump-102000",
    },
    {
      name: "Pump reducer nozzle",
      category: "StandardPumps",
      image: "/images/Pumps/102030.jpg",
      price: "199",
      slug: "pump-reducer-nozzle-102030",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102300.jpg",
      price: "199",
      slug: "premium-pump-102300",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102301.jpg",
      price: "199",
      slug: "premium-pump-102301",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102302.jpg",
      price: "199",
      slug: "premium-pump-102302",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102303.jpg",
      price: "199",
      slug: "premium-pump-102303",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102304.jpg",
      price: "199",
      slug: "premium-pump-102304",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102305.jpg",
      price: "199",
      slug: "premium-pump-102305",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102306.jpg",
      price: "199",
      slug: "premium-pump-102306",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102307.jpg",
      price: "199",
      slug: "premium-pump-102307",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102308.jpg",
      price: "199",
      slug: "premium-pump-102308",
    },
    {
      name: "Premium Pump",
      category: "PremiumPumps",
      image: "/images/Pumps/102309.jpg",
      price: "199",
      slug: "premium-pump-102309",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100100.jpg",
      price: "199",
      slug: "storage-lid-100100",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100101.jpg",
      price: "199",
      slug: "storage-lid-100101",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100102.jpg",
      price: "199",
      slug: "storage-lid-100102",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100103.jpg",
      price: "199",
      slug: "storage-lid-100103",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100104.jpg",
      price: "199",
      slug: "storage-lid-100104",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100105.jpg",
      price: "199",
      slug: "storage-lid-100105",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100106.jpg",
      price: "199",
      slug: "storage-lid-100106",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100107.jpg",
      price: "199",
      slug: "storage-lid-100107",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100108.jpg",
      price: "199",
      slug: "storage-lid-100108",
    },
    {
      name: "Storage Lid",
      category: "StorageLid",
      image: "/images/StorageLid/100109.jpg",
      price: "199",
      slug: "storage-lid-100109",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100300.jpg",
      price: "199",
      slug: "stretch-lid-100300",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100301.jpg",
      price: "199",
      slug: "stretch-lid-100301",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100302.jpg",
      price: "199",
      slug: "stretch-lid-100302",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100303.jpg",
      price: "199",
      slug: "stretch-lid-100303",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100304.jpg",
      price: "199",
      slug: "stretch-lid-100304",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100305.jpg",
      price: "199",
      slug: "stretch-lid-100305",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100306.jpg",
      price: "199",
      slug: "stretch-lid-100306",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100307.jpg",
      price: "199",
      slug: "stretch-lid-100307",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100308.jpg",
      price: "199",
      slug: "stretch-lid-100308",
    },
    {
      name: "Stretch Lid",
      category: "StretchLid",
      image: "/images/StretchLid/100309.jpg",
      price: "199",
      slug: "stretch-lid-100309",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100500.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100500",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100501.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100501",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100502.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100502",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100503.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100503",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100504.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100504",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100505.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100505",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100506.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100506",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100507.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100507",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100508.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100508",
    },
    {
      name: "Stumpy Spout Lid",
      category: "StumpySpoutLid",
      image: "/images/StumpySpoutLid/100509.jpg",
      price: "199",
      slug: "stumpy-spout-lid-100509",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100200.jpg",
      price: "199",
      slug: "utility-lid-100200",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100201.jpg",
      price: "199",
      slug: "utility-lid-100201",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100202.jpg",
      price: "199",
      slug: "utility-lid-100202",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100203.jpg",
      price: "199",
      slug: "utility-lid-100203",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100204.jpg",
      price: "199",
      slug: "utility-lid-100204",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100205.jpg",
      price: "199",
      slug: "utility-lid-100205",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100206.jpg",
      price: "199",
      slug: "utility-lid-100206",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100207.jpg",
      price: "199",
      slug: "utility-lid-100207",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100208.jpg",
      price: "199",
      slug: "utility-lid-100208",
    },
    {
      name: "Utility Lid",
      category: "UtilityLid",
      image: "/images/UtilityLid/100209.jpg",
      price: "199",
      slug: "utility-lid-100209",
    },
  ],
};

export default data;
